### ISSUE TITLE
Problem: Adding chain-maind keys will not be actually stored in disk

### ISSUE THREAD

**Issue by maannajjar** [crypto-org-chain/chain-main#437] opened 2021-03-27 17:10 UTC
**Describe the bug**
Whenever I try to add new key, or import new one. Then type list the keys it returns an empty list

**To Reproduce**
1. `chain-maind keys add Default`  (or `chain-maind keys import Default key_file`)
2. Type the encryption password for the key
3. `chain-maind` will print new key details with recovery keys
4.  Run `chain-maind keys list`, the output will be `[]`

**Expected behavior**
`chain-maind keys list` should output list including the newly added key

**Screenshots**
See following example (those keys are for testing only and are not used or maintained)
<img width="1098" alt="chain-maind" src="https://user-images.githubusercontent.com/2287702/112728360-4d51ab00-8efd-11eb-8389-b2cbc985dd74.png">

**Desktop (please complete the following information):**
 - OS: Linux , Pop OS 20.10 (Based on Ubuntu 20.10)
 - Browser None
 - Version Ubuntu 20.10 / `Linux 5.8.0-7642-generic #47~1612288990~20.10~b8113e7-Ubuntu SMP Wed Feb 3 02:27:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**
I tested the same commands in macOS and I was unable to reproduce this bug. Seems to be only happening in Linux

**Comment by tomtau** [comment] 2021-03-29 01:18
@maannajjar can you try with 1.2.0? also, do you run a headless distribution or do you have some GUI (e.g. gnome)? For the default keyring backend: https://docs.cosmos.network/master/run-node/keyring.html#the-os-backend -- one may need e.g. Seahorse on Linux.

**Comment by maannajjar** [comment] 2021-03-29 02:03
@tomtau I tried with 1.2.0 but it didn't work too. I'm running with Gnome GUI. When adding new key I do get the keyring prompt to create password for the new key (screenshot 1). I also opened the keyring management and I saw all the keys that were created by chain-maind (screenshot 2). I was able to unlock them using the passwords I used. I also tried unencrypted key (empty password), but that also didn't work. 


![keyring-prompt](https://user-images.githubusercontent.com/2287702/112777949-63509000-9011-11eb-8785-075df5c6be55.png)

![keyring](https://user-images.githubusercontent.com/2287702/112777956-68154400-9011-11eb-9fe6-4a1b7686909e.png)

**Comment by wolfwolker** [comment] 2021-03-29 16:04
same behaviour described by @maannajjar happening here. I'm using popOS 18.04 [derivated from ubuntu]

**Comment by leejw51crypto** [comment] 2021-03-30 01:22
i'm checking this issue in ubuntu

**Comment by leejw51crypto** [comment] 2021-03-30 02:29
reproduced it, i'll fix it

before fixed, you can use)
chain-maind keys list --keyring-backend file

**Comment by leejw51crypto** [comment] 2021-03-31 01:40
found the cause, working on now.

**Comment by Nawaz-Malik143** [comment] 2021-03-31 05:43
#407

**Comment by Nawaz-Malik143** [comment] 2021-03-31 05:44
#433

**Comment by Nawaz-Malik143** [comment] 2021-03-31 05:44
#439

**Comment by Nawaz-Malik143** [comment] 2021-03-31 05:44
#422

**Comment by Nawaz-Malik143** [comment] 2021-03-31 05:45
#422

**Comment by tomtau** [comment] 2021-03-31 06:18
should be fixed with https://github.com/99designs/keyring/pull/83

**Comment by leejw51crypto** [comment] 2021-03-31 07:33
to test,
add this line, top folder's go.mod
```
replace github.com/99designs/keyring => github.com/leejw51crypto/keyring v1.1.6-gnome
```

**Comment by leejw51crypto** [comment] 2021-04-01 01:50
before keyring is changed,
please use this branch  @maannajjar 

https://github.com/leejw51crypto/chain-main/tree/feature/437

**Comment by maannajjar** [comment] 2021-04-01 02:28
Awesome thanks @leejw51crypto I will try it out!

**Closed** 2021-04-22 01:41 UTC
Labels: need-investigation
