### ISSUE TITLE
Problem:  Block "0", Successful hashtx

### ISSUE THREAD

**Issue by HankFit247** [crypto-org-chain/chain-main#329] opened 2021-01-03 04:29 UTC
https://discord.com/channels/783264383978569728/790404424433926155/794394876102836234
"height":"0","txhash":"8D229F637BE8D8BFBEABB286A52D0EB2576B9109663A8F09A9BEF1F390701602"

**Comment by tomtau** [comment] 2021-01-04 01:22
reposting the message here (if it's the correct one):
```
Hello .I am trying to stake in crosseid 2 but getting error 

Insufficient fees
[10:41 AM]
I am just trying to stake 1 tcro
[10:41 AM]
My default address has 484000000 basetcro
[10:43 AM]
I also tried sending 5000 basetcro still getting the same error
[10:46 AM]
{"height":"0","txhash":"8D229F637BE8D8BFBEABB286A52D0EB2576B9109663A8F09A9BEF1F390701602","codespace":"sdk","code":13,"data":"","raw_log":"insufficient fees; got:  required: 5000basetcro: insufficient fee","logs":[],"info":"","gas_wanted":"200000","gas_used":"0","tx":null,"timestamp":""}
```

**Comment by HankFit247** [comment] 2021-01-04 02:27
> reposting the message here (if it's the correct one):
> 
> ```
> Hello .I am trying to stake in crosseid 2 but getting error 
> 
> Insufficient fees
> [10:41 AM]
> I am just trying to stake 1 tcro
> [10:41 AM]
> My default address has 484000000 basetcro
> [10:43 AM]
> I also tried sending 5000 basetcro still getting the same error
> [10:46 AM]
> {"height":"0","txhash":"8D229F637BE8D8BFBEABB286A52D0EB2576B9109663A8F09A9BEF1F390701602","codespace":"sdk","code":13,"data":"","raw_log":"insufficient fees; got:  required: 5000basetcro: insufficient fee","logs":[],"info":"","gas_wanted":"200000","gas_used":"0","tx":null,"timestamp":""}
> ```

Sometimes these report as Block "0" but however are actually successful.

Kindly include your build details, so that developers have more data to work with when trying to recreate the intermittent issue.

**Comment by tomtau** [comment] 2021-02-26 03:08
This looks like an issue related to the fee estimation (so can probably be resolved by tweaking the fee-related arguments) -- feel free to reopen this issue if this can be reproduced on 0.9.1 after the testnet upgrade

**Closed by tomtau** 2021-02-26 03:08 UTC
