### ISSUE TITLE
Problem: Chain-maind stop having new blocks

### ISSUE THREAD

**Issue by Galadrin** [crypto-org-chain/chain-main#368] opened 2021-01-31 21:04 UTC
**Describe the bug**
Chain-maind stop receive new blocks and refuse to stop

**To Reproduce**
*** On 1rst node ***
```
$ chain-maind status
{"NodeInfo":{"protocol_version":{"p2p":"8","block":"11","app":"0"},"id":"dca56f1f662a213af96e884b06d30bbc0a44f8e0","listen_addr":"tcp://0.0.0.0:26656","network":"crossfire","version":"","channels":"402021222330386061","moniker":"sentry1","other":{"tx_index":"on","rpc_address":"tcp://127.0.0.1:26657"}},"SyncInfo":{"latest_block_hash":"1005B045426FA948D661EEAA145D64FC50D11ABC607BE3195DB663B9D0D877BA","latest_app_hash":"75978082DE2EEC6328F119EB2C2662F12E91FC24FCA5C80592D97B101C31FB52","latest_block_height":"141395","latest_block_time":"2021-01-31T20:35:50.144016745Z","earliest_block_hash":"FF89F6722C823A88EF2853F255C1AA079F069A1C336562EFD398B724B81566C6","earliest_app_hash":"655D74EFAFB7A3C1E2D7542FADE76F44B307D3F78CE23813166F15A84DC57264","earliest_block_height":"130801","earliest_block_time":"2021-01-29T19:47:06.841170278Z","catching_up":false},"ValidatorInfo":{"Address":"F54D08F05DFCB27207E3606FCCDA6DFCB11AB6AB","PubKey":{"type":"tendermint/PubKeyEd25519","value":"w52R5+dPmphGt7dAhjYBnJIpslY/sSczMdtkm3Xwm5U="},"VotingPower":"13774827"}} 
```
*** on 2nd node ***
```
$ date && chain-maind status
Sun 31 Jan 2021 09:53:01 PM CET
{"NodeInfo":{"protocol_version":{"p2p":"8","block":"11","app":"0"},"id":"e2bffed633731b6ba211663893260fb6e715f871","listen_addr":"tcp://0.0.0.0:26656","network":"crossfire","version":"","channels":"40202122233038606100","moniker":"sentry1","other":{"tx_index":"on","rpc_address":"tcp://127.0.0.1:26657"}},"SyncInfo":{"latest_block_hash":"46B0C9BC968375461E796205331AC7052BBA628AAE7ADA891225356F1C469A3C","latest_app_hash":"BCEB0EA94325520435D105DA2B6270D4731B888A64B224FCCD008A0682889869","latest_block_height":"140651","latest_block_time":"2021-01-31T16:17:56.003429027Z","earliest_block_hash":"E840521E930798E87F85676C097489572A0A0F980BEACE98A8332095F86FCD62","earliest_app_hash":"C1586A2AF8182E265780D353D362C58E4700FBBC19EB74D29B05BB6EDA351F60","earliest_block_height":"134701","earliest_block_time":"2021-01-30T15:11:18.827883855Z","catching_up":false},"ValidatorInfo":{"Address":"CF7E28C370F7E532DE8EFE0D47E45756513A1857","PubKey":{"type":"tendermint/PubKeyEd25519","value":"b581WPivzYgrEPwLPruFjEo0zcJfGLBcbI5NcUTWH3g="},"VotingPower":"0"}}
```

try to restart the node, but the command didn't return
```
$ sudo systemctl stop chain-maind.service && sleep 10 && sudo systemctl start chain-maind 

^C
```
kill the service
`$ killall -KILL chain-maind`

`$ sudo systemctl start chain-maind `

```
$ date && chain-maind status
Sun 31 Jan 2021 09:55:13 PM CET
{"NodeInfo":{"protocol_version":{"p2p":"8","block":"11","app":"0"},"id":"e2bffed633731b6ba211663893260fb6e715f871","listen_addr":"tcp://0.0.0.0:26656","network":"crossfire","version":"","channels":"40202122233038606100","moniker":"sentry1","other":{"tx_index":"on","rpc_address":"tcp://127.0.0.1:26657"}},"SyncInfo":{"latest_block_hash":"46B0C9BC968375461E796205331AC7052BBA628AAE7ADA891225356F1C469A3C","latest_app_hash":"BCEB0EA94325520435D105DA2B6270D4731B888A64B224FCCD008A0682889869","latest_block_height":"140651","latest_block_time":"2021-01-31T16:17:56.003429027Z","earliest_block_hash":"E840521E930798E87F85676C097489572A0A0F980BEACE98A8332095F86FCD62","earliest_app_hash":"C1586A2AF8182E265780D353D362C58E4700FBBC19EB74D29B05BB6EDA351F60","earliest_block_height":"134701","earliest_block_time":"2021-01-30T15:11:18.827883855Z","catching_up":true},"ValidatorInfo":{"Address":"CF7E28C370F7E532DE8EFE0D47E45756513A1857","PubKey":{"type":"tendermint/PubKeyEd25519","value":"b581WPivzYgrEPwLPruFjEo0zcJfGLBcbI5NcUTWH3g="},"VotingPower":"0"}}
```

**Expected behavior**
chain-maind shall not stop fetching the new blocks
In this case, the catching_up flag shall be set to True

**VPS configuration :**
 - OS: Ubuntu 20.04 LTS server
 - 4 vCPU
 - 8GB RAM
 - 200GB SSD
 - 200Mbps

**Comment by esspam** [comment] 2021-01-31 21:25
If I may add my observations (having had the same problem several times):
- With port 26656 closed in the firewall the node runs without problems.
- as soon as port 26656 is opened, this problem occurs (not immediately but still reproducible) 
- even if I set the incoming connections to 0 in the config, this happens. I.e. just the possibility to connect (open port) is enough to cause the problem even if the client is supposed to close the connection immediately. 
Maybe this helps debugging.

**Comment by Galadrin** [comment] 2021-01-31 22:44
> * With port 26656 closed in the firewall the node runs without problems.
> * as soon as port 26656 is opened, this problem occurs (not immediately but still reproducible)

If you close the port 26656, you cannot received any connection from other peers.
It's the only port who need to be open in the firewall.

**Comment by Galadrin** [comment] 2021-01-31 22:46
> * also maybe important: restarting the chain-maind service waits for quite a long time. There must be some blocking happening (io / net?)

chain-maind wait for the end of the consensus before closing.
if the blocks period is too long, the closing period can be long.

**Comment by tomtau** [comment] 2021-02-04 02:44
@Galadrin just to make sure -- is this on Crossfire or Croeseid or your local network?

did you configure the `external_address` field in config.toml ?

**Comment by Galadrin** [comment] 2021-02-04 05:45
Hi,
It's on crossfire network.

I havn't set the `external_address`  field except for one of my sentry who have a ddns and not fixed IP.
I don't remember if this sentinel encountered this problem.

**Comment by tomtau** [comment] 2021-02-26 03:27
this may be due to unrealistic contestations on crossfire -- feel free to reopen this issue if this can be reproduced on 0.9.1 after the testnet upgrade

**Closed by tomtau** 2021-02-26 03:27 UTC
