### ISSUE TITLE
Problem: error 500 when sending a Tx throught the RPC api

### ISSUE THREAD

**Issue by Galadrin** [crypto-org-chain/chain-main#367] opened 2021-01-31 18:02 UTC
**Describe the bug**

The Tendermint RPC endpoint (port 1317) return error 500 when sending a Tx in `block` mode.

**To Reproduce**
Using the chainlib-py exemple, send a Tx in `block` mode
```
tx = Transaction(
        wallet=wallet_1,
        account_num=account_num,
        sequence=sequence,
        chain_id="crossfire",
        fee=100000,
        gas=300000,
        sync_mode = "block"
    )
```

**Expected behavior**
return code 200

**Screenshots**
```
{'tx': {'msg': [{'type': 'cosmos-sdk/MsgSend', 'value': {'from_address': 'cro13njqv0la9cw2mr80utsmeppmtxk57kfgtvs7ac', 'to_address': 'cro13njqv0la9cw2mr80utsmeppmtxk57kfgtvs7ac', 'amount': [{'denom': 'basetcro', 'amount': '1'}]}}], 'fee': {'gas': '200000', 'amount': [{'amount': '20000', 'denom': 'basetcro'}]}, 'memo': '', 'signatures': [{'signature': 'i761jb+oISCEB2ivIlOZfHFvLfxeStULHX711A+mymVCnU4beFqBwUKMLpBZPA2Nq4P62FTljLC6oXUpYNKwFA==', 'pub_key': {'type': 'tendermint/PubKeySecp256k1', 'value': 'A1cjIUeyMC+nnzyCSLaASe2zNTmApBDCFRN8LYCXGarm'}, 'account_number': '17', 'sequence': '3344450'}]}, 'mode': 'block'}
Traceback (most recent call last):
  File "transaction.py", line 136, in main
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:1317/txs

```

**Comment by tomtau** [comment] 2021-02-26 03:25
may be a duplicate of https://github.com/crypto-org-chain/chain-main/issues/328
feel free to reopen this issue if it is not and this can be reproduced on 0.9.1 after the testnet upgrade

**Closed by tomtau** 2021-02-26 03:25 UTC
